name: "Setup ccache"

inputs:
  MATRIX_OS:
    description: ''
    required: true
  MATRIX_ARCH:
    description: ''
    required: true
  EXTRA_KEY:
    description: ''
    required: false
  WORKSPACE_ROOT:
    description: 'workspace root to place ccache cache'
    required: true

description: ''

runs:
  using: "composite"
  steps:
    - name: CWD to workspace_root
      shell: bash
      run: |
        
        cd "${{ inputs.WORKSPACE_ROOT }}"
    
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.12
      with:
        key: ${{ inputs.MATRIX_OS }}-${{ inputs.MATRIX_ARCH }}-${{ inputs.EXTRA_KEY }}
        max-size: "1G"
        verbose: 2
        variant: ccache

    - name: Configure ccache
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      if: contains(inputs.MATRIX_OS, 'ubuntu') || contains(inputs.MATRIX_OS, 'macos')
      shell: bash
      run: |
        
        if [ x"${{ contains(inputs.MATRIX_OS, 'macos') }}" == x"true" ]; then
          echo "/usr/local/opt/ccache/libexec:/opt/homebrew/opt/ccache/libexec" >> $GITHUB_PATH
        else
          echo "/usr/lib/ccache:/usr/lib64/ccache:/usr/lib/ccache/bin" >> $GITHUB_PATH
        fi

    - name: Configure ccache
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      shell: bash
      run: |
        
        ccache -p
        ccache -z
        # See https://github.com/hendrikmuhs/ccache-action/issues/146
        ccache --set-config=compiler_check=content
        ccache --set-config=sloppiness=locale,time_macros
