#cmake -G Ninja \
#  -DLLVM_BUILD_TOOLS=OFF \
#  -DLLVM_INCLUDE_UTILS=OFF \
#  -DLLVM_INCLUDE_EXAMPLES=OFF \
#  -DLLVM_INCLUDE_TESTS=OFF \
#  -DLLVM_INCLUDE_BENCHMARKS=OFF \
#  -DLLVM_ENABLE_BINDINGS=OFF \
#  -DLLVM_BUILD_DOCS=OFF \
#  -DLLVM_ENABLE_OCAMLDOC=OFF \
#  -DLLVM_ENABLE_THREADS=OFF \
#  -DLLVM_ENABLE_BACKTRACES=OFF \
#  -DLLVM_ENABLE_PIC=OFF \
#  -DLLVM_ENABLE_UNWIND_TABLES=OFF \
#  -DLLVM_ENABLE_CRASH_OVERRIDES=OFF \
#  -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS=ON \
#  -DLLVM_ENABLE_PLUGINS=ON \
#  -DLLVM_ENABLE_TERMINFO=OFF \
#  -DLLVM_ENABLE_LIBXML2=OFF \
#  -DLLVM_ENABLE_LIBEDIT=OFF \
#  -DLLVM_ENABLE_LIBPFM=OFF \
#  -DLLVM_ENABLE_ZLIB=OFF \
#  -DLLVM_ENABLE_ZSTD=OFF \
#  -DLLVM_ENABLE_PROJECTS="mlir;llvm;lld" \
#  -DCMAKE_BUILD_TYPE=Release \
#  -DLLVM_TARGETS_TO_BUILD=AArch64 \
#  -DLLVM_HAVE_LIBXAR=OFF \
#  -B$PWD/build_mlir_symbols \
#  -S$PWD/../llvm-project/llvm
#
#cmake --build $PWD/build_mlir_symbols --target tools/mlir/tools/mlir-opt/mlir-opt.symbols
#cp ./build_mlir_symbols/tools/mlir/tools/mlir-opt/mlir-opt.symbols .
GENERATOR="Unix Makefiles"
GENERATOR="Ninja"

cmake -G $GENERATOR  \
  -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
  -DLLVM_BUILD_TOOLS=OFF \
  -DLLVM_INCLUDE_UTILS=OFF \
  -DLLVM_INCLUDE_EXAMPLES=OFF \
  -DLLVM_INCLUDE_TESTS=OFF \
  -DLLVM_INCLUDE_BENCHMARKS=OFF \
  -DLLVM_ENABLE_BINDINGS=OFF \
  -DLLVM_BUILD_DOCS=OFF \
  -DLLVM_ENABLE_OCAMLDOC=OFF \
  -DLLVM_ENABLE_THREADS=OFF \
  -DLLVM_ENABLE_BACKTRACES=OFF \
  -DLLVM_ENABLE_PIC=OFF \
  -DLLVM_ENABLE_UNWIND_TABLES=OFF \
  -DLLVM_ENABLE_CRASH_OVERRIDES=OFF \
  -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS=ON \
  -DLLVM_ENABLE_PLUGINS=ON \
  -DLLVM_ENABLE_TERMINFO=OFF \
  -DLLVM_ENABLE_LIBXML2=OFF \
  -DLLVM_ENABLE_LIBEDIT=OFF \
  -DLLVM_ENABLE_LIBPFM=OFF \
  -DLLVM_ENABLE_ZLIB=OFF \
  -DLLVM_ENABLE_ZSTD=OFF \
  -DLLVM_ENABLE_PROJECTS="mlir;llvm;lld" \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_TARGETS_TO_BUILD=WebAssembly \
  -DLLVM_TARGET_ARCH=wasm32-wasi \
  -DLLVM_DEFAULT_TARGET_TRIPLE=wasm32-wasi \
  -DLLVM_HAVE_LIBXAR=OFF \
  -DCMAKE_SYSTEM_NAME=Emscripten \
  -DLLVM_HOST_TRIPLE=arm64 \
  -DCROSS_TOOLCHAIN_FLAGS_NATIVE="-DCMAKE_C_COMPILER=clang;-DCMAKE_CXX_COMPILER=clang++" \
  -DCMAKE_EXE_LINKER_FLAGS="-sSTANDALONE_WASM=1 -sWASM=1 -sWASM_BIGINT=1 -sEXPORT_ALL=1 -sMODULARIZE=1 -sEXPORT_NAME=MLIRModule -sEXPORTED_RUNTIME_METHODS=cwrap,ccall,getValue,setValue,writeAsciiToMemory,wasmTable" \
  -B$PWD/build_mlir_wasm \
  -S$PWD/../llvm-project/llvm

cmake --build $PWD/build_mlir_wasm --target mlir-opt